name: Daily Paper Update

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 背景 时间 05:00 运行； UTC时间 = 北京时间 - 8小时
  workflow_dispatch:     # 可手动触发

jobs:
  run-daily-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.PAT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install beautifulsoup4 requests openai

      - name: Run Scraper
        env:
            API_ENDPOINT: ${{ secrets.API_ENDPOINT }} # WPS 多维表格接口
            BAILIAN_GPT_KEY: ${{ secrets.BAILIAN_GPT_KEY }}  # COZE 

        run: |
          while IFS= read -r line; do
            echo "$line"  # 逐行打印到 Action 控制台
          done < <(python -u paper_scraper.py 2>&1)      
      - name: Commit & Push Results
        run: |
          ls
          git config --global user.name 'lhnows'
          git config --global user.email 'lhnows@qq.com'
          git add .
          git commit -m "每日更新" 
          git push
